services:
  # Backend API Service
  - type: web
    name: clean-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    # buildCommand et startCommand gérés par Docker
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: clean-postgres
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
        length: 64
      - key: JWT_SECRET_KEY
        generateValue: true
        length: 64
      - key: CORS_ORIGINS
        value: '["https://clean-app.vercel.app","https://clean-app-git-main.vercel.app"]'
      - key: DEBUG
        value: False
      - key: ENVIRONMENT
        value: production
      - key: UPLOAD_MAX_SIZE
        value: 10485760
      - key: ALLOWED_EXTENSIONS
        value: '["jpg","jpeg","png","webp"]'
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 3600

  # PostgreSQL Database
  - type: pserv
    name: clean-postgres
    runtime: postgresql
    plan: free
    region: oregon
    databases:
      - name: clean_db
        user: clean_user