"""Add enterprise table

Revision ID: 003_add_enterprise_table
Revises: 
Create Date: 2025-09-02 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003_add_enterprise_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nom de l\'entreprise'),
    sa.Column('logo_url', sa.Text(), nullable=True, comment='URL du logo de l\'entreprise'),
    sa.Column('legal_form', sa.String(length=100), nullable=True, comment='Forme juridique (SARL, SAS, etc.)'),
    sa.Column('siret', sa.String(length=14), nullable=True, comment='Numéro SIRET'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprises')
    # ### end Alembic commands ###