name: Deploy to Staging

on:
  push:
    branches: [ develop, staging ]

env:
  REGISTRY: rg.fr-par.scw.cloud
  IMAGE_NAME: cleaning-backend-staging

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: nologin
        password: ${{ secrets.SCALEWAY_SECRET_KEY }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.SCALEWAY_PROJECT_ID }}/${{ env.IMAGE_NAME }}:staging
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to Staging Environment
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
        SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
        SCW_DEFAULT_REGION: fr-par
        SCW_DEFAULT_ZONE: fr-par-1
      run: |
        curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh
        ./scw config set access-key=$SCW_ACCESS_KEY
        ./scw config set secret-key=$SCW_SECRET_KEY
        ./scw config set default-project-id=$SCW_DEFAULT_PROJECT_ID
        ./scw config set default-region=$SCW_DEFAULT_REGION
        ./scw config set default-zone=$SCW_DEFAULT_ZONE
        
        ./scw container deploy \
          --name cleaning-backend-staging \
          --image ${{ env.REGISTRY }}/${{ secrets.SCALEWAY_PROJECT_ID }}/${{ env.IMAGE_NAME }}:staging \
          --env DATABASE_URL="${{ secrets.STAGING_DATABASE_URL }}" \
          --env FIREBASE_CREDENTIALS_PATH="/app/firebase-credentials.json" \
          --port 8000 \
          --cpu-limit 500 \
          --memory-limit 1024